apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-registry-couchdb-deployment
  labels:
    app: app-registry-couchdb
  namespace: ich-test
  generation: 1
spec:
  selector:
    matchLabels:
      app: app-registry-couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: app-registry-couchdb
    spec:
      nodeName: k8s-ich-test
      volumes:
      - name: couchdb
        hostPath:
          path: /home/curacloud/workspace/couchdb
      containers:
      - name: app-registry-couchdb
        image: couchdb:2.3
        ports:
        - name: admin
          containerPort: 5984
        volumeMounts:
        - name: couchdb
          mountPath: /opt/couchdb/data
---
apiVersion: v1
kind: Service
metadata:
  name: app-registry-couchdb-service
  namespace: ich-test
spec:
  ports:
  - name: admin
    port: 5984
    targetPort: 5984
    nodePort: 32184
  type: NodePort
  selector:
    app: app-registry-couchdb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-registry-deployment
  labels:
    app: app-registry
  namespace: ich-test
  generation: 1
spec:
  selector:
    matchLabels:
      app: app-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: app-registry
    spec:
      nodeName: k8s-ich-test
      volumes:
      - name: app-registry
        hostPath:
          path: /home/curacloud/stack/appRegistry      
      initContainers:
      - name: init-app-registry
        image: harbor.bj.keyayun.com/seal/app-register-service
        env:
        - name: KEYAYUN_REGISTRY_COUCHDB_URL
          value: http://app-registry-couchdb-service.ich-test:5984     
        command:
        - /go/scripts/feed.sh
      containers:
      - name: app-registry
        image: harbor.bj.keyayun.com/seal/app-register-service
        ports:
        - name: admin
          containerPort: 8081
        volumeMounts:
        - name: app-registry
          mountPath: /home
        env:
        - name: KEYAYUN_REGISTRY_COUCHDB_URL
          value: http://app-registry-couchdb-service.ich-test:5984
---
apiVersion: v1
kind: Service
metadata:
  name: app-registry-service
  namespace: ich-test
spec:
  ports:
  - name: admin
    port: 8081
    targetPort: 8081
    nodePort: 32181
  type: NodePort
  selector:
    app: app-registry