---
apiVersion: v1
kind: PersistentVolume
metadata:
  # 此名称唯一标识PVC。 将在以下部署中使用。
  name: couchbase-pv
  namespace: couchbase
spec:
  # 关于 access modes的更多细节，访问这里: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2048Gi
  nfs:
    server: 192.168.8.71
    path: "/couchbasebak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-pvc
  namespace: couchbase
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2048Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchbase-bak-deployment
  labels:
    app: couchbase-bak
  namespace: couchbase
spec:
  selector:
    matchLabels:
      app: couchbase-bak
  template:
    metadata:
      labels:
        app: couchbase-bak
    spec:
      nodeName: k8s-couchbase
      volumes:
      - name: couchbase-bak
        persistentVolumeClaim:
          claimName: couchbase-pvc 
      containers:
      - name: couchbase-bak
        image: couchbase/server:enterprise-6.0.1
        volumeMounts:
        - name: couchbase-bak
          mountPath: /bak