kind: List
apiVersion: v1
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: kibana-logging
    namespace: kube-system
    labels:
      k8s-app: kibana-logging
  spec:
    replicas: 1
    template:
      metadata:
        name: kibana-logging
        labels:
          app: kibana-logging
      spec:
        containers:
        - name: kibana-logging
          image: docker.elastic.co/kibana/kibana:6.4.0
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1000m
            requests:
              cpu: 500m       
          env:
          - name: ELASTICSEARCH_URL
            value: "http://es-cluster:9200"
          ports:
          - name: http
            name: ui
            containerPort: 5601
- apiVersion: v1
  kind: Service
  metadata:
    name: kibana-logging
    namespace: kube-logging
    labels:
      k8s-app: kibana-logging    
  spec:
    type: NodePort
    ports:
    - name: http
      port: 5601
      targetPort: 5601 
      nodePort: 32601
    selector:
      app: kibana-logging            
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: es-cluster
    namespace: kube-logging
  spec:
    serviceName: es-cluster
    replicas: 3
    selector:
      matchLabels:
        app: es-cluster
    template:
      metadata:
        name: es-cluster
        labels:
          app: es-cluster
          role: master
      spec:
        containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
          name: es
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
          - name: network.host
            value: "_site_"
          - name: node.name
            value: "${HOSTNAME}"
          - name: discovery.zen.ping.unicast.hosts
            value: "es-cluster"
          - name: discovery.zen.minimum_master_nodes
            value: "2"
          - name: cluster.name
            value: "k8s-logs-cluster"
          - name: node.master
            value: "true"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          volumeMounts:
          - name: es-cluster-storage
            mountPath: /usr/share/elasticsearch/data
        volumes:
          - name: es-cluster-storage
            emptyDir: {}
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: es-cluster-data
    namespace: kube-system
  spec:
    serviceName: es-cluster-data
    replicas: 3
    selector:
      matchLabels:
        app: es-cluster-data
    template:
      metadata:
        name: es-cluster-data
        labels:
          app: es-cluster-data
          author: shiqiang
          role: master
      spec:
        containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
          name: es-data
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
          - name: network.host
            value: "_site_"
          - name: node.name
            value: "${HOSTNAME}"
          - name: discovery.zen.ping.unicast.hosts
            value: "es-cluster"
          - name: discovery.zen.minimum_master_nodes
            value: "2"
          - name: cluster.name
            value: "k8s-logs-cluster"
          - name: node.master
            value: "false"
          - name: node.data
            value: "true"
          - name: node.ingest
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms128m -Xmx128m"
          volumeMounts:
          - name: es-cluster-storage
            mountPath: /usr/share/elasticsearch/data
        volumes:
          - name: es-cluster-storage
            emptyDir: {}
- apiVersion: v1
  kind: Service
  metadata: 
    name: es-cluster-nodeport
    namespace: kube-logging
  spec:
    type: NodePort
    ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 31200
    - name: tcp
      port: 9300
      targetPort: 9300
      nodePort: 31300
    selector:
      app: es-cluster
- apiVersion: v1
  kind: Service
  metadata:
    name: es-cluster
    namespace: kube-system
  spec:
    clusterIP: None
    ports:
    - name: http
      port: 9200
    - name: tcp
      port: 9300
    selector:
      app: es-cluster
