apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: mysql-init
        image: busybox
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_TEST_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pwd
              key: mysql-test-user-pwd
        command:  
        - sh
        - "-c"
        - |
          set -e
          rm -fr /var/lib/mysql/lost+found
          cat > /docker-entrypoint-initdb.d/mysql-testdb-init.sql <<EOF
          create database testdb default character set utf8;
          grant all on testdb.* to 'test'@'%' identified by '$MYSQL_TEST_USER_PASSWORD';
          flush privileges;
          EOF
          cat > /docker-entrypoint-initdb.d/mysql-appdb-init.sql <<EOF
          create table app(id int);
          insert into app values(1);
          commit;
          EOF
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - image: mysql/mysql-server:5.7
        name: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pwd
              key: mysql-root-pwd
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pwd
              key: mysql-app-user-pwd
        - name: MYSQL_USER
          value: app
        - name: MYSQL_DATABASE
          value: appdb
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/
        ports:
        - name: mysql
          containerPort: 3306
      volumes:
      - name: mysql-data
        hostPath:
          path: /Users/guojun/Documents/k8s/mysql-test
      - name: mysql-initdb
        emptyDir: {}
      - name: mysql-config
        configMap:
          name: mysql-config
---
apiVersion: v1
metadata:
  name: mysql-config
data:
  custom.cnf: |
        [mysqld]
        default_storage_engine=innodb
        skip_external_locking
        lower_case_table_names=1
        skip_host_cache
        skip_name_resolve
kind: ConfigMap