apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-example
  namespace: default
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  paused: false
  antiAffinity: true
  tls:
    static:
      member:
        serverSecret: couchbase-server-tls
      operatorSecret: couchbase-operator-tls
  authSecret: my-secret
  exposeAdminConsole: true
  adminConsoleServiceType: LoadBalancer
  adminConsoleServices:
    - data
  exposedFeatures:
    - client
  exposedFeatureServiceType: LoadBalancer
  softwareUpdateNotifications: true
  serverGroups:
    - us-east-1a
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 1000
  disableBucketManagement: false
  logRetentionTime: 604800s
  logRetentionCount: 20
  dns:
    domain: couchbase-0.us-east-1.example.com
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 1024
      replicas: 1
      ioPriority: high
      evictionPolicy: value-eviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive
  servers:
    # Name for the server configuration. It must be unique.
    - name: data_services
      size: 3
      services:
        - data
      serverGroups:
        - us-east-1a
      # Pod defines the policy to create pod for the couchbase pod.
      pod:
        nodeSelector:
          databases: "couchbase"
    - name: index_services
       # Size of the couchbase cluster.
      size: 2
      # The services to run on nodes
      services:
        - index
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-east-1a
      # Pod defines the policy to create pod for the couchbase pod.
      pod:
        nodeSelector:
          databases: "couchbase"
    - name: search_services
       # Size of the couchbase cluster.
      size: 1
      # The services to run on nodes
      services:
        - search
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-east-1a
      # Pod defines the policy to create pod for the couchbase pod.
      pod:
        nodeSelector:
          databases: "couchbase"
    - name: eventing_services
       # Size of the couchbase cluster.
      size: 1
      # The services to run on nodes
      services:
        - eventing
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-east-1a
      # Pod defines the policy to create pod for the couchbase pod.
      pod:
        nodeSelector:
          databases: "couchbase"
    - name: query_services
       # Size of the couchbase cluster.
      size: 1
      # The services to run on nodes
      services:
        - query
      # ServerGroups define the set of availability zones we want to distribute pods over.
      serverGroups:
        - us-east-1a
      pod:
        couchbaseEnv:
          - name: ENV1
            value: value
        envFrom:
          - secretRef:
              name: environment-secret
        resources:
          limits:
            cpu: 4
            memory: 8Gi
            storage: 100Gi
          requests:
            cpu: 2
            memory: 8Gi
            storage: 50Gi
        labels:
          couchbase_services: all
        annotations:
          couchbase.acme.com: production
        nodeSelector:
          instanceType: large
        tolerations:
          - key: app
            operator: Equal
            value: cbapp
            effect: NoSchedule
        automountServiceAccountToken: false
        imagePullSecrets:
          - name: my-pull-secret
        volumeMounts:
          default: couchbase
          data:  couchbase
          index: couchbase
          analytics:
            - couchbase
            - couchbase
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi